### ISSUE TITLE
No entiendo por qué usar esta reificación de award

### ISSUE THREAD

**Issue by ocorcho** [oeg-upm/morph-website#10]
https://github.com/oeg-upm/morph-website/blob/13f14369bc480375b038c9b3222d556001094bf4/obda/mapping.yaml#L281

**Comment by w0xter** [comment]
La idea es poder acceder a todos los awards que ha ganado una persona para que cuando entres en morph.oeg-upm.net/oscarcorcho se muestre una biografía y todos los papers, los premios y herramientas en las que ha participado

**Comment by ocorcho** [comment]
¿Pero no es posible simplemente usar un texto por cada award en lugar de convertirlo en un recurso? schema.org lo considera como un texto.
Por ejemplo:
oeg:oscarcorcho schema:award "Juan López de Peñalver. Real Academia de Ingeniería. 2016"

**Comment by w0xter** [comment]
Sii, así también se podría hacer. Pero entonces habría que darle una vuelta este [TM](https://github.com/oeg-upm/morph-website/blob/13f14369bc480375b038c9b3222d556001094bf4/obda/mapping.yaml#L130) también no??
Igual usar esto https://schema.org/WinAction

**Comment by ocorcho** [comment]
Cierto. WinAction no nos vale, pues no es lo mismo
Mañana tendremos sesión de validación de los mappings en la reunió de grupo ;-)

**Comment by dachafra** [comment]
se podría cerrar este issue?
