### ISSUE TITLE
Organisation

### ISSUE THREAD

**Issue by flowsta** [oeg-upm/morph-website#13]
Besides the use of schema states the mode "organization" (English US) instead of "organisation" (English UK), the mapping is like this:
`[schema:memberOf, $(organization), xsd:string]    #TODO: THIS HAS TO BE A URI OF TYPE ORGANISATION, E.G., REPRESENTING OEG
    - [schema:affiliation, $(organization), xsd:string]  #TODO: SAME HERE
    - [schema:worksFor, $(organization), xsd:string]    #TODO: THIS HAS TO BE A URI OF TYPE ORGANISATION, E.G., REPRESENTING OEG`

As far as my academic life has experienced when you apply for a conference or any other event or service the organisations required are university, faculty while the lab is included in the description of your role.
I was wondering whether you were taking this into account or my understanding is wrong.

**Comment by ocorcho** [comment]
This is different, as it is for our group, so we will probably add the URI of OEG here, although this does not mean that we may also add UPM and ETSIINF as well, since we can have as many triples as we wish.
